LIBFT =	Libft/libft.a

SRCS = main.c

all:	$(LIBFT) $(SRCS)
	gcc *.c Libft/src/GNL/get_next_line.c lib/MLX42/build/libmlx42.a Libft/libft.a -ldl -lglfw -pthread -lm -lreadline -g3 #-fsanitize=address #-Wall -Werror -Wextra 
